# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go build env
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        cache-dependency-path: go.sum

    - name: Build
      run: go build -v ./... -o /flagbot

    - name: Upload binary
      uses: actions/upload-artifact@v4.3.1
      with:
        name: flagbot
        path: /flagbot
